POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pmw3360
MOUSE_SHARED_EP = no             # Shared USB endpoint

SPLIT_KEYBOARD = yes
SERIAL_DRIVER = usart

BOOTLOADER = rp2040

DYNAMIC_MACRO_ENABLE = yes
